name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        uses: GabrielBB/xvfb-action@v1.2
        with:
          run: >
            mvn -s settings.xml -B clean verify org.pitest:pitest-maven:mutationCoverage
            sonar:sonar coveralls:report -DrepoToken=$COVERALLS_TOKEN -Pjacoco
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}